### ISSUE TITLE
VOT evaluation problem: Tracker execution interrupted: Did not receive response

### ISSUE THREAD

**Issue by universefall** [ZjjConan/Optimized-MDNet#1]
Hello,thank u for sharing the code. I try to evaluate the performance on VOT2016 and configure the "tracker_OptMDNet_Opt.m" and copy files in `vot/vot_tracker_settings` into my vot workspace. Also change the matcovnet path in "setup_optmdnet.m". And I run run_experiment in VOT toolkit. It happens following problem:
run_experiments
Initializing workspace ...
Verifying native components ...
Experiment baseline
  Tracker OptMDNet_Opt
    Sequence bag
      Repetition 1
      Tracker execution interrupted: Did not receive response.
Is it related to the version of MatCovNet? Thanks

**Comment by ZjjConan** [comment]
Hi, I can successfully run the code on my computer. Did you find any error files in your local path (error_reports in the root path of Optimized-MDNet)?

**Comment by ZjjConan** [comment]
> Hello,thank u for sharing the code. I try to evaluate the performance on VOT2016 and configure the "tracker_OptMDNet_Opt.m" and copy files in `vot/vot_tracker_settings` into my vot workspace. Also change the matcovnet path in "setup_optmdnet.m". And I run run_experiment in VOT toolkit. It happens following problem:
> run_experiments
> Initializing workspace ...
> Verifying native components ...
> Experiment baseline
> Tracker OptMDNet_Opt
> Sequence bag
> Repetition 1
> Tracker execution interrupted: Did not receive response.
> Is it related to the version of MatCovNet? Thanks

Hi, I can successfully run the code on my computer. Did you find any error files in your local path (error_reports in the root path of Optimized-MDNet)?

**Comment by ZjjConan** [comment]
> Hello,thank u for sharing the code. I try to evaluate the performance on VOT2016 and configure the "tracker_OptMDNet_Opt.m" and copy files in `vot/vot_tracker_settings` into my vot workspace. Also change the matcovnet path in "setup_optmdnet.m". And I run run_experiment in VOT toolkit. It happens following problem:
> run_experiments
> Initializing workspace ...
> Verifying native components ...
> Experiment baseline
> Tracker OptMDNet_Opt
> Sequence bag
> Repetition 1
> Tracker execution interrupted: Did not receive response.
> Is it related to the version of MatCovNet? Thanks

Hi, I add a demo to check whether your 3rdparties are well installed. You can check it by "run_demo" for "Bolt2" tracking.

**Comment by universefall** [comment]
> > Hello,thank u for sharing the code. I try to evaluate the performance on VOT2016 and configure the "tracker_OptMDNet_Opt.m" and copy files in `vot/vot_tracker_settings` into my vot workspace. Also change the matcovnet path in "setup_optmdnet.m". And I run run_experiment in VOT toolkit. It happens following problem:
> > run_experiments
> > Initializing workspace ...
> > Verifying native components ...
> > Experiment baseline
> > Tracker OptMDNet_Opt
> > Sequence bag
> > Repetition 1
> > Tracker execution interrupted: Did not receive response.
> > Is it related to the version of MatCovNet? Thanks
> 
> Hi, I add a demo to check whether your 3rdparties are well installed. You can check it by "run_demo" for "Bolt2" tracking.

ok， I will try it

**Comment by universefall** [comment]
> > > Hello,thank u for sharing the code. I try to evaluate the performance on VOT2016 and configure the "tracker_OptMDNet_Opt.m" and copy files in `vot/vot_tracker_settings` into my vot workspace. Also change the matcovnet path in "setup_optmdnet.m". And I run run_experiment in VOT toolkit. It happens following problem:
> > > run_experiments
> > > Initializing workspace ...
> > > Verifying native components ...
> > > Experiment baseline
> > > Tracker OptMDNet_Opt
> > > Sequence bag
> > > Repetition 1
> > > Tracker execution interrupted: Did not receive response.
> > > Is it related to the version of MatCovNet? Thanks
> > 
> > 
> > Hi, I add a demo to check whether your 3rdparties are well installed. You can check it by "run_demo" for "Bolt2" tracking.
> 
> ok， I will try it

hello， I found the error report saying **Undefined variable "dagnn" or class "dagnn.DagNN.loadobj".**  I check my matcovnet directory and didn't find function related to dagnn. It seems to be released in the latter version matconvnet. While, the original MDNet uses a earlier version of matconvnet. So I' m going to use a latest version.

**Comment by universefall** [comment]
I applied the 25th version of matconvnet. When it runs at network initilization stage in **mdnet_finetune_hnm.m** , saying **Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'** .My GPU memory is 2 GB. It seems be not enough for training.

**Comment by ZjjConan** [comment]
Yeah, It will take more memory (~ 4G) than original MDNet for tracking. I usually use a card with more than 4G memory for testing.

**Comment by universefall** [comment]
I used other computer with more memory. demo works well, but vot toolkit shows problem with trax not alive

**Comment by ZjjConan** [comment]
Maybe you need to use latest vot toolkit for testing.

**Comment by universefall** [comment]
Thank you！I update the Matlab to 2017b and CUDA 8.0 with Cudnn v5, finally fixed the problem.

**Comment by ZjjConan** [comment]
Glod to hear about that. I hope this code will be helpful for your research. I will close this issue soon.

**Comment by ZjjConan** [comment]
> Thank you！I update the Matlab to 2017b and CUDA 8.0 with Cudnn v5, finally fixed the problem. 

BTW, what is your EAO score on VOT-2016 dataset. I usually can get ~0.35 on that dataset.

**Comment by universefall** [comment]
> > Thank you！I update the Matlab to 2017b and CUDA 8.0 with Cudnn v5, finally fixed the problem.
> 
> BTW, what is your EAO score on VOT-2016 dataset. I usually can get ~0.35 on that dataset.

I got EAO of 0.3677 on VOT2016.  And overall precision rate 0.896 on OTB2015, which is lower than the result given by the paper of **MDNet**

**Comment by ZjjConan** [comment]
Yes, as it has some random process. I can get similar scores on these two datasets. The VOT2016 results are significantly better than the original MDNet, or some extensions such as VITAL (0.323). On OTB dataset, sometimes, I got better performance than MDNet (0.677 AUC). The mean AUC scores for 5 time running are 0.672, which is however slightly slower than MDNet.
